<blockquote>
  <p> Cette page est consacrée à une présentation générale de la personne de Marcel Ehyua M'BIA. Mais ne vous inquiétez surtout pas, ce n'est certainnement pas pour faire de la politique. </p>
  <p>Si donc l'horizon est si dégagé, allons-y sans tarder.</p>
  <p><strong>A l'Etat civil:</strong></p>
  <p>Jusque là, MEM s'appelle par César <u>MARCEL EHYUA M'BIA N'GUESSAN</u>. Mais ne vous génez surtout pas nous vous en prions, le plein droit vous est accordé de tronquer ce nom en un simple trigrame: MEM. D'ailleur d'ici bientôt, (et quand on dis bientôt c'est très bientôt), ce nom &quot;N'GUESSAN&quot; sera rayé de tout les fichier de César; enfin... en ce qui  concerne MEM. Pourquoi ? Eh bien parce qu'il n'est pas sensé lui appartenir, c'est aussi simple que ça! beuhr voilà, vous savez tous sur lui. Öh pardon, nous en étions qu'à l'Etat civil.</p>
  <p>Si si, et comment l'aurais-je oublier ? Mon patron a bien évidemment  un compte <a href="http://www.facebook.com/marcelehyua">Facebook</a>, et même un de Twitter. Mais bon, pour une seul personne ça suffit non ? (On n'a rien contre les chinois hein!). Ok, voyons donc qui est MEM au quotidien ?</p>
  <p><strong>Au quotidien:</strong></p>
  <p>Toujours fidèle et égale à lui-même, MEM reste celui qu'il a toujours été dépuis qu'il a su qu'il possède le &quot;JE&quot;: c'est-à-dire un jeune homme très élégant (je dirais même mieu, il est <a href="http://www.facebook.com/elegance1">né élégant</a>) et pas seulment avec les filles (et bonne nouvelle pour vous les filles, mon patron n'est pas un charmant coureur de pagne, hé pardon, de jupette, ôh mais merde heuheu!!!! De jupon, voilà!). Il est en outre un homme assez objectif et réaliste surtout très optimiste (c'est pas si étonnant, ça fait baucoup de bien, épuis qui a proscrit du bonnheur le paradi sur la terre). Les études ? vous pressez pas! nous en adviendron. D'ailleur allons-y.</p>
  <p><strong>Côté études:</strong></p>
  <p>Puff! Pas si térrible hein! Mon très très jeune patron était encore en cour préparatif aux école d'ingénieurie quelque part vers la deuxième années du BTS. Quel domaine ? Je vous laisses déviner, mais un indice est qu'il est tres fryant de l'informatique et de l'anglais. Ok je sais, c'est ridicule, de toute façon vous l'avez déja la reponse. MEM est TECHNITIEN SUPPERIEUR en INFORMATIQUE / DEVELOPPEMENT D'APPLICATIONS. E tce site internet qui lui est particulièrement dédié est l'oeuvre de ses propres doigts. Pas mal hein! Mais non.... Qui a dit qu'il a fait les lettres modernes. Eh! Qui a parlé d' OXFORD ou d' AVARD ? Mais non... Monsieur M'BIA mon patron est un humble ivoirien qui a jusque là étudié dans de très humbles écoles et ne me demandez pas de pub svp. Oui bien sûr, il est en ses projets d'étudier dans une école plus prestigieuse, mais bon, là tout dépendra du mode de vie que lui assignera son attachement à DIEU; (très croyant hein je vous en pris).</p>
  <p>Quoi, pourquoi si jeune et si modeste, est-il mon patron ? Non mais ne me dites pas que vous estes tombés dans le piège de l'apparance! Pour un prince agni, mon patron a quant même droit à un minimum de notabilité dont le sécrétaire particulier que lui suis. Mais bon, oublions la royautée, c'est caduc. Ok, voyons qui il est dans la société.</p>
  <p><strong>Vie social:</strong></p>
  <p>Co-fondateur de l'entreprise informatique EASY-INTERFACE et par ricoché responsable du département WEB c'est à dire la EIWA. pas mal non ? Souhaitez nous donc bocoup de courage et que le marché nous soit facilement pénétrable.</p>
  <p><a href="#">Lire la suite--&gt;</a></p>
</blockquote>
